language: php
before_install:
    - if [[ "$(php --version | grep -cim1 xdebug)" -ge 1 ]]; then phpenv config-rm xdebug.ini; fi
git:
    depth: 5
install:
    - composer install
php:
    - 7.0
    - 7.1
script:
    - mkdir -p build
    - phpdbg -qrr -f vendor/phpspec/phpspec/bin/phpspec --config=phpspec_coverage.yml run
after_success:
    - composer require --dev satooshi/php-coveralls:dev-master
    - travis_retry php vendor/bin/coveralls -v
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - travis_retry php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
